:Author: Kevin Jin
:Email:
:Date: 10/05/2022
:Revision: version#
:License: Public Domain

= Project: Smart Mailbox System v1

The majority of mailboxes in use today are just metal boxes with mechanical locks that mail carriers and residents need to unlock manually to place the mail inside or to retrieve them. Some indoor mailbox suites for apartments have a small gap to slide in the mail for delivery without unlockingthe mailbox, but they carry an increased risk of mail theft. This project experiments with digitizing the experience of using a mailbox, add attempts to address the need for fast and secure access to mailboxes and notifications for delivery. 

== Step 1: Installation
Please describe the steps to install this project.

For example:

1. Open this file
2. Edit as you like
3. Release to the World!

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── sketch123.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact: 

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Part number | Quantity
| R1 | 10k Resistor   | 1234-abcd   | 10       
| L1 | Red LED        | 2345-asdf   | 5        
| A1 | Arduino Zero   | ABX00066    | 1        
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
