:Author: Kaiyuan Jin
:Email:
:Date: 10/05/2022
:Revision: version#1
:License: Public Domain

= Project: Smart Mailbox System v1

The majority of mailboxes in use today are just metal boxes with mechanical locks that mail carriers and residents need to unlock manually to place the mail inside or to retrieve them. Some indoor mailbox suites for apartments have a small gap to slide in the mail for delivery without unlockingthe mailbox, but they carry an increased risk of mail theft. This project experiments with digitizing the experience of using a mailbox, add attempts to address the need for fast and secure access to mailboxes and notifications for delivery. 

== Step 1: Setup server and email notice
For this version of the project, Arduino IoT Cloud was used as the host server to simplify the setup. Please visit https://docs.arduino.cc/cloud/iot-cloud to create a server. To setup the email notification, please visit https://ifttt.com/.

== Step 2: Assemble the circuit

Assemble the circuit with the chip chosen. 

===BOM
1. Arduino Nano 33 for IoT
2. Servo
3. RFID sensor and tags
4. Buzzer

== Step 3: Load the code
Upload the code via the online Arduino IoT Cloud code editor. 


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
