// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onLockCommandChange();

bool doorState;
bool lockCommand;

void initProperties(){

  ArduinoCloud.addProperty(doorState, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(lockCommand, READWRITE, ON_CHANGE, onLockCommandChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
